"""
=========================================================
pdf_utils.py
---------------------------------------------------------
Utility functions for PDF generation.

Shared by:
    - pdf_sections.py
    - pdf_tables.py
    - pdf_report_generator.py
=========================================================
"""

from datetime import datetime

from reportlab.lib import colors
from reportlab.pdfgen.canvas import Canvas


# =========================================================
# Safe Value Formatter
# =========================================================

def safe_value(value, default="N/A"):
    """
    Returns a printable value.

    None -> N/A
    """

    if value is None:
        return default

    if value == "":
        return default

    return str(value)


# =========================================================
# Date Formatter
# =========================================================

def format_datetime(dt_string):
    """
    Converts ISO datetime into a readable format.
    """

    try:
        dt = datetime.fromisoformat(dt_string)

        return dt.strftime("%d %B %Y  %I:%M %p")

    except Exception:
        return safe_value(dt_string)


# =========================================================
# Float Formatter
# =========================================================

def format_number(value, digits=2):
    """
    Returns a rounded numeric string.
    """

    try:
        return f"{float(value):.{digits}f}"

    except Exception:
        return safe_value(value)


# =========================================================
# Percentage Formatter
# =========================================================

def format_percent(value, digits=2):
    """
    Converts numeric value into percentage string.
    """

    try:
        return f"{float(value):.{digits}f}%"

    except Exception:
        return safe_value(value)


# =========================================================
# Horizontal Line
# =========================================================

def draw_horizontal_line(canvas: Canvas,
                         y,
                         left=40,
                         right=555):
    """
    Draws a separator line.
    """

    canvas.setStrokeColor(colors.grey)

    canvas.line(left, y, right, y)


# =========================================================
# Header
# =========================================================

def draw_header(canvas: Canvas, doc):
    """
    Draws page header.
    """

    canvas.saveState()

    canvas.setFont("Helvetica-Bold", 13)

    canvas.drawString(
        40,
        810,
        "Solar Wind Deployment Intelligence"
    )

    draw_horizontal_line(canvas, 803)

    canvas.restoreState()


# =========================================================
# Footer
# =========================================================

def draw_footer(canvas: Canvas, doc):
    """
    Draw footer and page number.
    """

    canvas.saveState()

    draw_horizontal_line(canvas, 40)

    canvas.setFont("Helvetica", 8)

    canvas.drawString(
        40,
        25,
        "Generated by Solar Wind Deployment Intelligence Engine"
    )

    canvas.drawRightString(
        555,
        25,
        f"Page {doc.page}"
    )

    canvas.restoreState()


# =========================================================
# Combined Page Layout
# =========================================================

def add_page_layout(canvas: Canvas, doc):
    """
    Adds header + footer to every page.
    """

    draw_header(canvas, doc)

    draw_footer(canvas, doc)